build_file: core.py
options:
  - '--clean'
  - '-y'

data:
  - "resources/splash_screen.png;."
  - "resources/bg.png;."
  - "resources/GUI.ui;."
  - "resources/images/logo.ico;."
  - "settings/config.yaml;./settings"
  - "ffmpeg/*.exe;./ffmpeg"

logo: logo.ico

upx: upx394w

name: octopus